services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass

  web-1:
    image: mywebapp
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  web-2:
    image: mywebapp
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web-1
      - web-2


volumes:
  redis_data:
  db_data:
